// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC59QVkjY4cGn3vUFTKYas9bnkBCOZK-ic',
    appId: '1:95075364865:web:ed1b1c3b829fb8d1435000',
    messagingSenderId: '95075364865',
    projectId: 'salesconcierge-1aca2',
    authDomain: 'salesconcierge-1aca2.firebaseapp.com',
    storageBucket: 'salesconcierge-1aca2.appspot.com',
    measurementId: 'G-K87KRQH5CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIh-pOHgA66xg7qAlSLIwoFX-H7EM_Gyk',
    appId: '1:95075364865:android:88efc23d298ab60b435000',
    messagingSenderId: '95075364865',
    projectId: 'salesconcierge-1aca2',
    storageBucket: 'salesconcierge-1aca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcq0WP7Z3O42JS8Cg9TAD0KBHJmR6Y5-k',
    appId: '1:95075364865:ios:710fbfc716305594435000',
    messagingSenderId: '95075364865',
    projectId: 'salesconcierge-1aca2',
    storageBucket: 'salesconcierge-1aca2.appspot.com',
    iosClientId:
        '95075364865-t5oc4vc3ps36scr1ufsnbb6779hlbs8b.apps.googleusercontent.com',
    iosBundleId: 'com.armaansolutions.asmvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcq0WP7Z3O42JS8Cg9TAD0KBHJmR6Y5-k',
    appId: '1:95075364865:ios:9345ef996a390c8a435000',
    messagingSenderId: '95075364865',
    projectId: 'salesconcierge-1aca2',
    storageBucket: 'salesconcierge-1aca2.appspot.com',
    iosClientId:
        '95075364865-d7n4uh0kl7a00m913010n0vgo5vu57lg.apps.googleusercontent.com',
    iosBundleId: 'com.armaansolutions.asmvp.RunnerTests',
  );
}
